name: build
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
      actions: write
    env:
      CI: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      # - if: steps.git_diff.outputs.has_changes
      #   name: Update status check (if changed)
      #   run: gh api -X POST /repos/${{ github.event.pull_request.head.repo.full_name
      #     }}/check-runs -F name="build" -F head_sha="$(git rev-parse HEAD)" -F
      #     status="completed" -F conclusion="success"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - if: steps.git_diff.outputs.has_changes
      #   name: Cancel workflow (if changed)
      #   run: gh api -X POST /repos/${{ github.event.pull_request.head.repo.full_name
      #     }}/actions/runs/${{ github.run_id }}/cancel
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: echo ${{ github.ref }}